version: "3.9"
services:
  dmn-app-postgres:
    image: postgres
    container_name: 'dmn-app-postgres'
    environment:
    - POSTGRES_DB=dmn-app
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
    - 12200:5432
